import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient({
  datasources: { db: { url: process.env.DIRECT_URL } },
})

async function main() {
  console.log('🌱 Seeding Comprehensive H&H Pharmacy master database...')

  // Create Admin with Owners
  const hashedPassword = await bcrypt.hash('HHPharmacy@2024', 12)
  const admin = await prisma.admin.upsert({
    where: { email: 'admin@hhpharmacy.in' },
    update: {
      name: 'Nishant Choudhary & Harsh Kashyap',
      phone: '7827558443 / 8171093455',
    },
    create: {
      name: 'Nishant Choudhary & Harsh Kashyap',
      email: 'admin@hhpharmacy.in',
      passwordHash: hashedPassword,
      phone: '7827558443',
      role: 'owner',
    },
  })
  console.log('✅ Admin initialized:', admin.email)

  // Demo Customer
  const customerPassword = await bcrypt.hash('demo123', 10)
  await prisma.user.upsert({
    where: { email: 'rahul.demo@gmail.com' },
    update: {},
    create: {
      name: 'Rahul Sharma (Demo Customer)',
      email: 'rahul.demo@gmail.com',
      passwordHash: customerPassword,
      phone: '9876543210',
    },
  })

  // 12 Standard Pharmacy Categories
  const categories = [
    { id: 1, name: 'Pain & Fever Relief', nameHindi: 'दर्द एवं बुखार', icon: '💊', color: '#EF4444', sortOrder: 1 },
    { id: 2, name: 'Cold, Cough & Allergy', nameHindi: 'सर्दी, खांसी और एलर्जी', icon: '🤒', color: '#F59E0B', sortOrder: 2 },
    { id: 3, name: 'Acidity, Gas & Digestion', nameHindi: 'गैस, एसिडिटी और पाचन', icon: '🫁', color: '#3B82F6', sortOrder: 3 },
    { id: 4, name: 'Antibiotics & Infection', nameHindi: 'एंटीबायोटिक (Rx)', icon: '🧬', color: '#8B5CF6', sortOrder: 4 },
    { id: 5, name: 'Vitamins, Calcium & Energy', nameHindi: 'विटामिन और पोषण', icon: '🌿', color: '#10B981', sortOrder: 5 },
    { id: 6, name: 'Pain Gels, Balms & Sprays', nameHindi: 'दर्द निवारक जेल और बाम', icon: '🧴', color: '#EC4899', sortOrder: 6 },
    { id: 7, name: 'Ayurvedic & Immunity', nameHindi: 'आयुर्वेदिक एवं हर्बल', icon: '🌱', color: '#84CC16', sortOrder: 7 },
    { id: 8, name: 'Diabetes Care & Strips', nameHindi: 'शुगर / मधुमेह देखभाल', icon: '🩸', color: '#06B6D4', sortOrder: 8 },
    { id: 9, name: 'Heart, BP & Cholesterol', nameHindi: 'बीपी और हृदय स्वास्थ्य', icon: '❤️', color: '#DC2626', sortOrder: 9 },
    { id: 10, name: 'Baby Care & Pediatric', nameHindi: 'शिशु एवं बाल देखभाल', icon: '👶', color: '#F97316', sortOrder: 10 },
    { id: 11, name: 'Eye, Ear & First Aid', nameHindi: 'आंख, कान व प्राथमिक उपचार', icon: '🩹', color: '#7C3AED', sortOrder: 11 },
    { id: 12, name: 'Skin Care & Antiseptics', nameHindi: 'त्वचा और एंटीसेप्टिक', icon: '✨', color: '#64748B', sortOrder: 12 },
  ]

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: cat,
      create: cat,
    })
  }
  console.log('✅ Categories seeded: 12')

  // Master Indian Medicine Dataset (All daily Indian pharmacy essentials)
  const masterMedicines = [
    // 1. Pain & Fever Relief
    {
      name: 'Dolo 650mg Tablet',
      nameHindi: 'डोलो 650mg टैबलेट',
      genericName: 'Paracetamol 650mg',
      brand: 'Dolo',
      manufacturer: 'Micro Labs Ltd',
      description: 'Dolo 650 is India\'s top recommended paracetamol tablet for fast fever reduction and body pain relief.',
      usageInstructions: 'Take 1 tablet every 4-6 hours when fever or body ache occurs. Maximum 4 tablets in 24 hours.',
      sideEffects: 'Generally safe. Rare: nausea. Avoid taking with alcohol or other paracetamol products.',
      mrp: 34.50, sellingPrice: 30, discountPercent: 13,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Crocin 650mg Tablet',
      nameHindi: 'क्रोसिन 650mg टैबलेट',
      genericName: 'Paracetamol 650mg Fast Release',
      brand: 'Crocin',
      manufacturer: 'GlaxoSmithKline (GSK)',
      description: 'Crocin 650 provides quick relief from fever, headache, backache, toothache and muscular pain.',
      usageInstructions: '1 tablet with a glass of water every 4 to 6 hours as needed.',
      sideEffects: 'Well-tolerated. Do not exceed recommended daily limit.',
      mrp: 35.00, sellingPrice: 30, discountPercent: 14,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Combiflam Tablet',
      nameHindi: 'कॉम्बीफ्लाम टैबलेट',
      genericName: 'Ibuprofen 400mg + Paracetamol 325mg',
      brand: 'Combiflam',
      manufacturer: 'Sanofi India',
      description: 'Dual-action combination for severe headache, toothache, muscle spasm, and joint pain.',
      usageInstructions: 'Take 1 tablet after meals. Avoid on empty stomach.',
      sideEffects: 'Stomach irritation, mild nausea in sensitive individuals.',
      mrp: 48.00, sellingPrice: 40, discountPercent: 16,
      unitType: 'strip', unitsPerPack: 20,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 1', cover: 'Red Label',
    },
    {
      name: 'Meftal-Spas Tablet',
      nameHindi: 'मेफ्टाल-स्पास टैबलेट',
      genericName: 'Mefenamic Acid 250mg + Dicyclomine 10mg',
      brand: 'Meftal-Spas',
      manufacturer: 'Blue Cross Laboratories',
      description: 'Effective antispasmodic medication for menstrual cramps, stomach pain, and intestinal spasms.',
      usageInstructions: '1 tablet after food as prescribed for acute stomach cramps.',
      sideEffects: 'Dizziness, dry mouth, blurred vision.',
      mrp: 52.00, sellingPrice: 45, discountPercent: 13,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 2', cover: 'Yellow Tag',
    },
    {
      name: 'Zerodol-P Tablet',
      nameHindi: 'जीरोडोल-पी टैबलेट',
      genericName: 'Aceclofenac 100mg + Paracetamol 325mg',
      brand: 'Zerodol-P',
      manufacturer: 'Ipca Laboratories',
      description: 'Non-steroidal anti-inflammatory drug (NSAID) for arthritis, spondylitis, back pain, and dental pain.',
      usageInstructions: '1 tablet twice daily with food.',
      sideEffects: 'Heartburn, nausea, abdominal pain.',
      mrp: 68.00, sellingPrice: 58, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 2', cover: 'Green Label',
    },
    {
      name: 'Saridon Tablet',
      nameHindi: 'सेरिडॉन टैबलेट',
      genericName: 'Paracetamol + Propyphenazone + Caffeine',
      brand: 'Saridon',
      manufacturer: 'Piramal Healthcare',
      description: 'Fast acting headache specialist tablet with triple action formula.',
      usageInstructions: 'Take 1 tablet with water. Do not take more than 3 tablets a day.',
      sideEffects: 'Mild restlessness, insomnia if taken late night due to caffeine.',
      mrp: 46.00, sellingPrice: 40, discountPercent: 13,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
    },

    // 2. Acidity, Gas & Digestion
    {
      name: 'Pan-D Capsule',
      nameHindi: 'पैन-डी कैप्सूल',
      genericName: 'Pantoprazole 40mg + Domperidone 30mg SR',
      brand: 'Pan-D',
      manufacturer: 'Alkem Laboratories',
      description: 'Prescription acid-reflux and gas relief capsule for GERD, hyperacidity, bloating, and heartburn.',
      usageInstructions: 'Take 1 capsule early morning on an empty stomach (30 mins before breakfast).',
      sideEffects: 'Dry mouth, headache, mild diarrhea.',
      mrp: 220.00, sellingPrice: 187, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
      imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Pantocid 40mg Tablet',
      nameHindi: 'पैंटोसिड 40mg टैबलेट',
      genericName: 'Pantoprazole Sodium 40mg',
      brand: 'Pantocid',
      manufacturer: 'Sun Pharmaceutical',
      description: 'Proton pump inhibitor (PPI) that reduces acid produced in the stomach. Treats ulcers and severe acidity.',
      usageInstructions: '1 tablet once daily in the morning before food.',
      sideEffects: 'Nausea, dizziness, flatulence.',
      mrp: 175.00, sellingPrice: 148, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
      imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 1', cover: 'Green Label',
    },
    {
      name: 'Digene Antacid Gel Mint 200ml',
      nameHindi: 'डाइजीन जेल मिंट 200ml',
      genericName: 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
      brand: 'Digene',
      manufacturer: 'Abbott Healthcare',
      description: 'High acid neutralizing formula for rapid relief from gas, acidity, bloating and heartburn.',
      usageInstructions: 'Take 2 teaspoons (10ml) after meals or at bedtime.',
      sideEffects: 'Generally safe. Mild laxative effect if overdosed.',
      mrp: 145.00, sellingPrice: 125, discountPercent: 14,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 3,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
    },
    {
      name: 'Eno Fruit Salt Regular 100g',
      nameHindi: 'ईनो फ्रूट सॉल्ट 100g',
      genericName: 'Svarjiksara + Nimbukamlam (Effervescent)',
      brand: 'Eno',
      manufacturer: 'GlaxoSmithKline (GSK)',
      description: 'Starts working in 6 seconds against acidity and stomach burning.',
      usageInstructions: 'Dissolve 1 teaspoon in a glass of water and drink immediately.',
      sideEffects: 'Safe. Avoid in severe sodium-restricted diets.',
      mrp: 160.00, sellingPrice: 140, discountPercent: 12,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 3,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
    },
    {
      name: 'Rantac 150mg Tablet',
      nameHindi: 'रैनटेक 150mg टैबलेट',
      genericName: 'Ranitidine Hydrochloride 150mg',
      brand: 'Rantac',
      manufacturer: 'J.B. Chemicals',
      description: 'H2 receptor blocker for heartburn, indigestion, and acid-related stomach discomfort.',
      usageInstructions: '1 tablet twice daily before meals.',
      sideEffects: 'Headache, constipation, fatigue.',
      mrp: 42.00, sellingPrice: 36, discountPercent: 14,
      unitType: 'strip', unitsPerPack: 30,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
      imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Red Label',
    },

    // 3. Cold, Cough & Allergy
    {
      name: 'Sinarest Tablet',
      nameHindi: 'सिनारेस्ट टैबलेट',
      genericName: 'Paracetamol + Phenylephrine + Chlorpheniramine',
      brand: 'Sinarest',
      manufacturer: 'Centaur Pharmaceuticals',
      description: 'All-in-one cold and flu tablet for runny nose, blocked sinuses, watery eyes and fever.',
      usageInstructions: '1 tablet 3 times a day after meals.',
      sideEffects: 'Drowsiness, mild dry mouth. Avoid driving after taking.',
      mrp: 65.00, sellingPrice: 55, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 3', cover: 'Blue Cover',
    },
    {
      name: 'Allegra 120mg Tablet',
      nameHindi: 'एलेग्रा 120mg टैबलेट',
      genericName: 'Fexofenadine Hydrochloride 120mg',
      brand: 'Allegra',
      manufacturer: 'Sanofi India',
      description: 'Non-sedating antihistamine for seasonal allergic rhinitis, skin allergy, sneezing and pollen allergy.',
      usageInstructions: '1 tablet once daily with water. Non-drowsy formula.',
      sideEffects: 'Headache, dizziness (rare).',
      mrp: 232.00, sellingPrice: 198, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 2,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 3', cover: 'Green Label',
    },
    {
      name: 'Otrivin Adult Nasal Drops 10ml',
      nameHindi: 'ओट्रिविन नेजल ड्रॉप्स 10ml',
      genericName: 'Xylometazoline Hydrochloride 0.1%',
      brand: 'Otrivin',
      manufacturer: 'GlaxoSmithKline (GSK)',
      description: 'Opens blocked nose in 25 seconds and provides breathing relief for up to 12 hours.',
      usageInstructions: '2-3 drops in each nostril 2-3 times daily. Do not use for more than 5 consecutive days.',
      sideEffects: 'Mild nasal burning or dryness.',
      mrp: 75.00, sellingPrice: 65, discountPercent: 13,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Benadryl Cough Syrup 100ml',
      nameHindi: 'बेनाड्रिल कफ सिरप 100ml',
      genericName: 'Diphenhydramine + Ammonium Chloride + Sodium Citrate',
      brand: 'Benadryl',
      manufacturer: 'Johnson & Johnson',
      description: 'Doctor trusted formula for relief from wet and dry cough, throat tickle, and chest congestion.',
      usageInstructions: '10ml (2 teaspoons) every 4 hours for adults.',
      sideEffects: 'Drowsiness, mild sedation.',
      mrp: 140.00, sellingPrice: 120, discountPercent: 14,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
      imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 3', cover: 'Red Label',
    },
    {
      name: 'Vicks VapoRub 50g',
      nameHindi: 'विक्स वेपोरब 50g',
      genericName: 'Menthol + Camphor + Eucalyptus Oil',
      brand: 'Vicks',
      manufacturer: 'Procter & Gamble (P&G)',
      description: '6 cough and cold symptom relief ointment for topical application and steam inhalation.',
      usageInstructions: 'Apply on chest, throat and back. For steam inhalation: 1-2 teaspoons in hot water.',
      sideEffects: 'Safe for external use only. Keep away from eyes.',
      mrp: 165.00, sellingPrice: 145, discountPercent: 12,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 2', cover: 'Blue Cover',
    },

    // 4. Antibiotics (Schedule H / H1)
    {
      name: 'Augmentin 625 Duo Tablet',
      nameHindi: 'ऑगमेंटिन 625 डुओ टैबलेट',
      genericName: 'Amoxycillin 500mg + Clavulanic Acid 125mg',
      brand: 'Augmentin',
      manufacturer: 'GlaxoSmithKline (GSK)',
      description: 'Broad-spectrum antibiotic for bacterial infections of respiratory tract, lungs, ENT, skin and soft tissue.',
      usageInstructions: 'Take 1 tablet twice daily with meals as prescribed. Complete the full course.',
      sideEffects: 'Diarrhea, nausea, vomiting.',
      mrp: 223.50, sellingPrice: 190, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H1', requiresPrescription: true, categoryId: 4,
      imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
    },
    {
      name: 'Azithral 500mg Tablet',
      nameHindi: 'एज़िथ्रल 500mg टैबलेट',
      genericName: 'Azithromycin 500mg',
      brand: 'Azithral',
      manufacturer: 'Alembic Pharmaceuticals',
      description: 'Macrolide antibiotic for throat infections, tonsillitis, sinus, pneumonia, and skin bacterial infections.',
      usageInstructions: '1 tablet once daily for 3 to 5 days as prescribed. Take 1 hour before or 2 hours after meals.',
      sideEffects: 'Stomach cramp, loose stools, nausea.',
      mrp: 130.00, sellingPrice: 110, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 5,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 4,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
    },
    {
      name: 'Taxim-O 200mg Tablet',
      nameHindi: 'टैक्सिम-ओ 200mg टैबलेट',
      genericName: 'Cefixime 200mg',
      brand: 'Taxim-O',
      manufacturer: 'Alkem Laboratories',
      description: 'Cephalosporin antibiotic for typhoid fever, urinary tract infection (UTI), ENT infections.',
      usageInstructions: '1 tablet twice daily with food as prescribed by doctor.',
      sideEffects: 'Loose motions, indigestion, gas.',
      mrp: 115.00, sellingPrice: 98, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H1', requiresPrescription: true, categoryId: 4,
      imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
    },

    // 5. Vitamins, Calcium & Energy
    {
      name: 'Shelcal 500mg Tablet',
      nameHindi: 'शेलकैल 500mg टैबलेट',
      genericName: 'Calcium 500mg + Vitamin D3 250 IU',
      brand: 'Shelcal',
      manufacturer: 'Torrent Pharmaceuticals',
      description: 'Essential calcium and vitamin D3 supplement for strong bones, joints, teeth and osteoporosis prevention.',
      usageInstructions: '1 tablet daily after lunch or dinner.',
      sideEffects: 'Well tolerated. Rare: constipation if water intake is low.',
      mrp: 135.00, sellingPrice: 115, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 1', cover: 'Green Label',
    },
    {
      name: 'Becosules Z Capsule',
      nameHindi: 'बेकोसूल्स जेड कैप्सूल',
      genericName: 'Vitamin B-Complex + Vitamin C + Zinc',
      brand: 'Becosules',
      manufacturer: 'Pfizer India',
      description: 'Treats mouth ulcers, general weakness, improves immunity and energy metabolism.',
      usageInstructions: '1 capsule daily after a meal.',
      sideEffects: 'Harmless bright yellow urine.',
      mrp: 55.00, sellingPrice: 47, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 20,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 1', cover: 'Green Label',
    },
    {
      name: 'Limcee 500mg Chewable Tablet (Orange)',
      nameHindi: 'लिमसी 500mg चबाने वाली गोली',
      genericName: 'Vitamin C (Ascorbic Acid) 500mg',
      brand: 'Limcee',
      manufacturer: 'Abbott Healthcare',
      description: 'Tasty orange chewable Vitamin C for immunity, skin health, and wound healing.',
      usageInstructions: 'Chew 1 tablet daily. Do not swallow whole.',
      sideEffects: 'Safe vitamin supplement.',
      mrp: 26.00, sellingPrice: 22, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
    },
    {
      name: 'Neurobion Forte Tablet',
      nameHindi: 'न्यूरोबियन फोर्ट टैबलेट',
      genericName: 'Vitamin B1 + B2 + B3 + B5 + B6 + B12',
      brand: 'Neurobion',
      manufacturer: 'Procter & Gamble (P&G)',
      description: 'Nerve health supplement for tingling, numbness in fingers/toes, muscle weakness and nerve pain.',
      usageInstructions: '1 tablet daily after food.',
      sideEffects: 'Safe multivitamin.',
      mrp: 44.00, sellingPrice: 38, discountPercent: 14,
      unitType: 'strip', unitsPerPack: 30,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
      imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Evion 400mg Vitamin E Capsule',
      nameHindi: 'एवियन 400mg विटामिन ई कैप्सूल',
      genericName: 'Tocopheryl Acetate (Vitamin E) 400mg',
      brand: 'Evion',
      manufacturer: 'Merck / P&G',
      description: 'Powerful antioxidant for glowing skin, hair strength, muscle health, and cellular repair.',
      usageInstructions: '1 capsule daily or puncture for topical skin application.',
      sideEffects: 'Safe fat-soluble vitamin.',
      mrp: 41.00, sellingPrice: 35, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
      imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 2', cover: 'Green Label',
    },

    // 6. Pain Gels, Balms & Sprays
    {
      name: 'Volini Pain Relief Gel 30g',
      nameHindi: 'वोलिनी जेल 30g',
      genericName: 'Diclofenac Diethylamine + Methyl Salicylate + Menthol',
      brand: 'Volini',
      manufacturer: 'Sun Pharma',
      description: 'Instant pain relief formula for back pain, joint ache, neck sprain and sports injury.',
      usageInstructions: 'Gently apply 3-4 times daily on the painful area. Do not massage vigorously.',
      sideEffects: 'Mild redness if applied on broken skin.',
      mrp: 165.00, sellingPrice: 140, discountPercent: 15,
      unitType: 'tube', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 6,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
    },
    {
      name: 'Moov Pain Relief Cream 50g',
      nameHindi: 'मूव क्रीम 50g',
      genericName: 'Nilgiri Oil + Wintergreen Oil + Mint Extract',
      brand: 'Moov',
      manufacturer: 'Reckitt Benckiser',
      description: '100% Ayurvedic active ingredients for warm soothing relief from backache and muscle stiffness.',
      usageInstructions: 'Spread gently on affected muscle. Massage till absorbed.',
      sideEffects: 'Warm tingling sensation.',
      mrp: 215.00, sellingPrice: 185, discountPercent: 14,
      unitType: 'tube', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 6,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Red Label',
    },

    // 7. Ayurvedic & Immunity
    {
      name: 'Dabur Chyawanprash 1kg (Double Immunity)',
      nameHindi: 'डाबर च्यवनप्राश 1kg',
      genericName: 'Amla + Ashwagandha + 41 Ayurvedic Herbs',
      brand: 'Dabur',
      manufacturer: 'Dabur India Ltd',
      description: 'Time-tested Ayurvedic formulation with 2X immunity against seasonal infections, colds and coughs.',
      usageInstructions: '1 teaspoonful twice daily for adults, followed by warm milk or water.',
      sideEffects: 'Safe for all ages. Diabetics should choose sugar-free version.',
      mrp: 410.00, sellingPrice: 350, discountPercent: 15,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 3', cover: 'Green Label',
    },
    {
      name: 'Liv.52 DS Tablet 60s',
      nameHindi: 'लिव.52 डीएस टैबलेट 60s',
      genericName: 'Himsra + Kasani Herbal Liver Formula',
      brand: 'Himalaya',
      manufacturer: 'Himalaya Wellness',
      description: 'Double strength liver protective tablet. Improves appetite, digestion and protects liver from toxins.',
      usageInstructions: '1-2 tablets twice daily before meals.',
      sideEffects: 'Safe herbal formulation.',
      mrp: 210.00, sellingPrice: 180, discountPercent: 14,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
      imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 3', cover: 'Green Label',
    },
    {
      name: 'Patanjali Ashwagandha Capsule 20s',
      nameHindi: 'पतंजलि अश्वगंधा कैप्सूल',
      genericName: 'Withania Somnifera Extract',
      brand: 'Patanjali',
      manufacturer: 'Patanjali Ayurved Ltd',
      description: 'Ayurvedic stress buster, vitality and energy booster.',
      usageInstructions: '1 capsule twice daily with warm milk.',
      sideEffects: 'Safe Ayurvedic herb.',
      mrp: 120.00, sellingPrice: 102, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 20,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
      imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 3', cover: 'Yellow Tag',
    },
    {
      name: 'Dabur Pudin Hara Pearls 10s',
      nameHindi: 'डाबर पुदीन हरा पर्ल्स',
      genericName: 'Pudina Satva (Mentha Oil)',
      brand: 'Pudin Hara',
      manufacturer: 'Dabur India',
      description: 'Fast cooling relief from stomach ache, gas, and indigestion with pure mint pearls.',
      usageInstructions: '1 pearl with a glass of water when stomach discomfort occurs.',
      sideEffects: 'Safe herbal remedy.',
      mrp: 30.00, sellingPrice: 26, discountPercent: 13,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Green Label',
    },

    // 8. Diabetes & BP
    {
      name: 'Glycomet 500mg Tablet',
      nameHindi: 'ग्लाइकोमेट 500mg टैबलेट',
      genericName: 'Metformin Hydrochloride 500mg',
      brand: 'Glycomet',
      manufacturer: 'USV Pvt Ltd',
      description: 'First-line medication for blood sugar control in Type-2 diabetes.',
      usageInstructions: 'Take with or after meals as prescribed by physician.',
      sideEffects: 'Stomach upset, metallic taste initially.',
      mrp: 38.00, sellingPrice: 32, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 8,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
    },
    {
      name: 'Telma 40mg Tablet',
      nameHindi: 'टेल्मा 40mg टैबलेट',
      genericName: 'Telmisartan 40mg',
      brand: 'Telma',
      manufacturer: 'Glenmark Pharmaceuticals',
      description: 'Blood pressure regulation medicine for hypertension to protect heart and kidneys.',
      usageInstructions: '1 tablet daily at the same time each day.',
      sideEffects: 'Dizziness, low BP if dehydrated.',
      mrp: 245.00, sellingPrice: 208, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 15,
      drugSchedule: 'H', requiresPrescription: true, categoryId: 9,
      imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf B', rack: 'Rack 2', cover: 'Red Label',
    },
    {
      name: 'OneTouch Select Plus Test Strips 25s',
      nameHindi: 'वनटच सेलेक्ट प्लस टेस्ट स्ट्रिप्स 25s',
      genericName: 'Blood Glucose Test Strips',
      brand: 'OneTouch',
      manufacturer: 'LifeScan / J&J',
      description: 'Accurate self-testing blood glucose strips for home diabetes management.',
      usageInstructions: 'Insert strip in meter, apply tiny blood droplet from finger prick.',
      sideEffects: 'Diagnostic test strip.',
      mrp: 650.00, sellingPrice: 550, discountPercent: 15,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 8,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 2', cover: 'Yellow Tag',
    },

    // 9. Skin Care & Antiseptics
    {
      name: 'Betadine 5% Antiseptic Ointment 20g',
      nameHindi: 'बेटाडाइन 5% ऑइंटमेंट 20g',
      genericName: 'Povidone Iodine 5% w/w',
      brand: 'Betadine',
      manufacturer: 'Win-Medicare',
      description: 'Microbicidal ointment for cuts, wounds, burns, and minor skin infections.',
      usageInstructions: 'Clean wound and apply thin layer 1-2 times daily.',
      sideEffects: 'Mild burning on fresh cut.',
      mrp: 85.00, sellingPrice: 72, discountPercent: 15,
      unitType: 'tube', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 12,
      imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf A', rack: 'Rack 2', cover: 'Yellow Tag',
    },
    {
      name: 'Band-Aid Classic Strips 10s',
      nameHindi: 'बैंड-एड क्लासिक स्ट्रिप्स 10s',
      genericName: 'Medicated Adhesive Bandages',
      brand: 'Band-Aid',
      manufacturer: 'Johnson & Johnson',
      description: 'Water resistant medicated wound protection strips.',
      usageInstructions: 'Apply on cleaned cut or blister. Change daily.',
      sideEffects: 'Safe.',
      mrp: 45.00, sellingPrice: 38, discountPercent: 15,
      unitType: 'strip', unitsPerPack: 10,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 11,
      imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
    },
    {
      name: 'Dettol Antiseptic Liquid 100ml',
      nameHindi: 'डेटॉल एंटीसेप्टिक लिक्विड 100ml',
      genericName: 'Chloroxylenol 4.8% w/v',
      brand: 'Dettol',
      manufacturer: 'Reckitt Benckiser',
      description: 'Iconic household antiseptic for first aid, cuts, bites and hygienic cleaning.',
      usageInstructions: 'Dilute with water for first-aid wound washing.',
      sideEffects: 'For external use only.',
      mrp: 45.00, sellingPrice: 40, discountPercent: 11,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 11,
      imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&auto=format&fit=crop&q=80',
      shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Green Label',
    },
    {
      name: 'Calpol 250mg Peadiatric Suspension 60ml',
      nameHindi: 'कैलपोल 250mg सस्पेंशन 60ml',
      genericName: 'Paracetamol 250mg / 5ml (Strawberry Flavour)',
      brand: 'Calpol',
      manufacturer: 'GlaxoSmithKline (GSK)',
      description: 'Gentle on little stomachs. Fast fever and pain relief for infants and growing children.',
      usageInstructions: 'Dose as per child body weight prescribed by pediatrician. Shake well before use.',
      sideEffects: 'Safe pediatric formulation.',
      mrp: 54.00, sellingPrice: 46, discountPercent: 15,
      unitType: 'bottle', unitsPerPack: 1,
      drugSchedule: 'OTC', requiresPrescription: false, categoryId: 10,
      imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=500&auto=format&fit=crop&q=80',
      shelf: 'Shelf C', rack: 'Rack 1', cover: 'Red Label',
    },
  ]

  for (const med of masterMedicines) {
    const existing = await prisma.medicine.findFirst({ where: { name: med.name } })

    let medicineId: number
    if (existing) {
      const updated = await prisma.medicine.update({
        where: { id: existing.id },
        data: {
          name: med.name,
          nameHindi: med.nameHindi,
          genericName: med.genericName,
          brand: med.brand,
          manufacturer: med.manufacturer,
          description: med.description,
          usageInstructions: med.usageInstructions,
          sideEffects: med.sideEffects,
          mrp: med.mrp,
          sellingPrice: med.sellingPrice,
          discountPercent: med.discountPercent,
          unitType: med.unitType,
          unitsPerPack: med.unitsPerPack,
          drugSchedule: med.drugSchedule,
          requiresPrescription: med.requiresPrescription,
          categoryId: med.categoryId,
          imageUrl: med.imageUrl,
          isActive: true,
        },
      })
      medicineId = updated.id
    } else {
      const created = await prisma.medicine.create({
        data: {
          name: med.name,
          nameHindi: med.nameHindi,
          genericName: med.genericName,
          brand: med.brand,
          manufacturer: med.manufacturer,
          description: med.description,
          usageInstructions: med.usageInstructions,
          sideEffects: med.sideEffects,
          mrp: med.mrp,
          sellingPrice: med.sellingPrice,
          discountPercent: med.discountPercent,
          unitType: med.unitType,
          unitsPerPack: med.unitsPerPack,
          drugSchedule: med.drugSchedule,
          requiresPrescription: med.requiresPrescription,
          categoryId: med.categoryId,
          imageUrl: med.imageUrl,
          isActive: true,
        },
      })
      medicineId = created.id
    }

    // Upsert fresh active batch (Safe expiry: June 2028)
    const existingBatch = await prisma.medicineBatch.findFirst({
      where: { medicineId },
    })

    if (!existingBatch) {
      await prisma.medicineBatch.create({
        data: {
          medicineId,
          batchNumber: `BATCH-HH-${medicineId.toString().padStart(4, '0')}-2028`,
          expiryDate: new Date('2028-06-30'),
          totalQuantity: 250,
          currentQuantity: 250,
          purchasePrice: med.sellingPrice * 0.75,
        },
      })
    }

    // Set shop shelf location
    await prisma.medicineLocation.upsert({
      where: { medicineId },
      update: {
        shelfLabel: med.shelf,
        rackNumber: med.rack,
        section: 'Middle',
        coverLabel: med.cover,
        description: 'Main dispensary zone',
      },
      create: {
        medicineId,
        shelfLabel: med.shelf,
        rackNumber: med.rack,
        section: 'Middle',
        coverLabel: med.cover,
        description: 'Main dispensary zone',
      },
    })
  }

  console.log(`✅ Master medicine dataset seeded (${masterMedicines.length} medicines populated with real images & batches)!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
