import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

const comprehensiveIndianMedicines = [
  // --- Category 1: Pain & Fever Relief ---
  {
    name: 'Dolo 650mg Tablet',
    nameHindi: 'डोलो 650mg टैबलेट',
    genericName: 'Paracetamol 650mg',
    brand: 'Dolo',
    manufacturer: 'Micro Labs Ltd',
    description: 'India\'s most prescribed paracetamol tablet for high fever, severe headache and acute body pain relief.',
    usageInstructions: '1 tablet every 4-6 hours. Do not exceed 4 tablets in 24 hours.',
    sideEffects: 'Safe. Avoid taking with alcohol or duplicate paracetamol drugs.',
    mrp: 34.50, sellingPrice: 30, discountPercent: 13,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Crocin 650mg Fast Release Tablet',
    nameHindi: 'क्रोसिन 650mg टैबलेट',
    genericName: 'Paracetamol 650mg Optizorb',
    brand: 'Crocin',
    manufacturer: 'GlaxoSmithKline (GSK)',
    description: 'Fast acting fever reducer and pain reliever for fever, back pain, joint pain and migraine.',
    usageInstructions: '1 tablet with water every 4 to 6 hours as needed.',
    sideEffects: 'Well-tolerated.',
    mrp: 35.00, sellingPrice: 30, discountPercent: 14,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Combiflam Tablet',
    nameHindi: 'कॉम्बीफ्लाम टैबलेट',
    genericName: 'Ibuprofen 400mg + Paracetamol 325mg',
    brand: 'Combiflam',
    manufacturer: 'Sanofi India',
    description: 'Dual-action combination for severe toothache, muscular pain, inflammation and fever.',
    usageInstructions: '1 tablet after food. Do not take on an empty stomach.',
    sideEffects: 'Mild stomach irritation, heartburn.',
    mrp: 48.00, sellingPrice: 40, discountPercent: 16,
    unitType: 'strip', unitsPerPack: 20, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 1', cover: 'Red Label',
  },
  {
    name: 'Meftal-Spas Tablet',
    nameHindi: 'मेफ्टाल-स्पास टैबलेट',
    genericName: 'Mefenamic Acid 250mg + Dicyclomine 10mg',
    brand: 'Meftal-Spas',
    manufacturer: 'Blue Cross Laboratories',
    description: 'Specialist antispasmodic for menstrual cramps, abdominal pain and intestinal colic.',
    usageInstructions: '1 tablet after meals when cramps occur.',
    sideEffects: 'Drowsiness, dry mouth.',
    mrp: 52.00, sellingPrice: 45, discountPercent: 13,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H', requiresPrescription: true, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Yellow Tag',
  },
  {
    name: 'Zerodol-P Tablet',
    nameHindi: 'जीरोडोल-पी टैबलेट',
    genericName: 'Aceclofenac 100mg + Paracetamol 325mg',
    brand: 'Zerodol-P',
    manufacturer: 'Ipca Laboratories',
    description: 'High-potency pain relief for arthritis, spondylitis, swelling, dental pain and backache.',
    usageInstructions: '1 tablet twice daily after meals.',
    sideEffects: 'Nausea, indigestion.',
    mrp: 68.00, sellingPrice: 58, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H', requiresPrescription: true, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Green Label',
  },
  {
    name: 'Saridon Headache Relief Tablet',
    nameHindi: 'सेरिडॉन टैबलेट',
    genericName: 'Paracetamol + Propyphenazone + Caffeine',
    brand: 'Saridon',
    manufacturer: 'Piramal Healthcare',
    description: 'Starts relieving tough headache within 30 minutes with caffeine booster formula.',
    usageInstructions: '1 tablet with water. Max 3 tablets daily.',
    sideEffects: 'Mild restlessness.',
    mrp: 46.00, sellingPrice: 40, discountPercent: 13,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Disprin 325mg Effervescent Tablet',
    nameHindi: 'डिस्प्रिन 325mg टैबलेट',
    genericName: 'Soluble Aspirin (Acetylsalicylic Acid) 325mg',
    brand: 'Disprin',
    manufacturer: 'Reckitt Benckiser',
    description: 'Soluble pain reliever and blood thinner for fast relief from migraine and toothache.',
    usageInstructions: 'Dissolve 1-2 tablets in a glass of water and drink immediately.',
    sideEffects: 'Stomach irritation. Not for children under 16.',
    mrp: 14.00, sellingPrice: 12, discountPercent: 14,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
  },
  {
    name: 'Sumo Tablet',
    nameHindi: 'सुमो टैबलेट',
    genericName: 'Nimesulide 100mg + Paracetamol 325mg',
    brand: 'Sumo',
    manufacturer: 'Alkem Laboratories',
    description: 'Powerful anti-inflammatory tablet for acute acute muscular pain, joint fever and injury pain.',
    usageInstructions: '1 tablet after food as prescribed. Avoid long term continuous use.',
    sideEffects: 'Stomach acidity, liver enzyme elevation.',
    mrp: 138.00, sellingPrice: 118, discountPercent: 14,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Red Label',
  },

  // --- Category 2: Acidity, Gas & Digestion ---
  {
    name: 'Pan-D Capsule',
    nameHindi: 'पैन-डी कैप्सूल',
    genericName: 'Pantoprazole 40mg + Domperidone 30mg SR',
    brand: 'Pan-D',
    manufacturer: 'Alkem Laboratories',
    description: 'Top prescribed medicine for severe acidity, gas, nausea, GERD, and chest burning.',
    usageInstructions: 'Take 1 capsule on an empty stomach 30 minutes before morning breakfast.',
    sideEffects: 'Dry mouth, headache.',
    mrp: 220.00, sellingPrice: 187, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Pantocid 40mg Tablet',
    nameHindi: 'पैंटोसिड 40mg टैबलेट',
    genericName: 'Pantoprazole Sodium 40mg',
    brand: 'Pantocid',
    manufacturer: 'Sun Pharmaceutical',
    description: 'Inhibits gastric acid production to heal peptic ulcers and prevent acid reflux.',
    usageInstructions: '1 tablet daily in the morning with a glass of water.',
    sideEffects: 'Flatulence, dizziness.',
    mrp: 175.00, sellingPrice: 148, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 1', cover: 'Green Label',
  },
  {
    name: 'Omez 20mg Capsule',
    nameHindi: 'ओमेज 20mg कैप्सूल',
    genericName: 'Omeprazole 20mg',
    brand: 'Omez',
    manufacturer: 'Dr. Reddy\'s Laboratories',
    description: 'Effective proton pump inhibitor for heartburn, sour burps and indigestion.',
    usageInstructions: '1 capsule 30 minutes before morning food.',
    sideEffects: 'Abdominal pain, mild headache.',
    mrp: 65.00, sellingPrice: 55, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 20, drugSchedule: 'H', requiresPrescription: true, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 1', cover: 'Yellow Tag',
  },
  {
    name: 'Digene Antacid Gel Mint 200ml',
    nameHindi: 'डाइजीन जेल मिंट 200ml',
    genericName: 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
    brand: 'Digene',
    manufacturer: 'Abbott Healthcare',
    description: 'Sugar-free high neutralizing antacid syrup for instant relief from heartburn and gas.',
    usageInstructions: 'Take 2 teaspoons (10ml) after meals or when burning occurs.',
    sideEffects: 'Safe.',
    mrp: 145.00, sellingPrice: 125, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
  },
  {
    name: 'Eno Fruit Salt Lemon 100g Bottle',
    nameHindi: 'ईनो लेमन 100g',
    genericName: 'Svarjiksara + Nimbukamlam Effervescent',
    brand: 'Eno',
    manufacturer: 'GlaxoSmithKline (GSK)',
    description: 'Works in 6 seconds against heavy stomach acidity and heartburn.',
    usageInstructions: 'Mix 1 teaspoon in a glass of water and drink immediately.',
    sideEffects: 'Safe. Avoid in high sodium diets.',
    mrp: 160.00, sellingPrice: 140, discountPercent: 12,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
  },
  {
    name: 'Gelusil MPS Antacid Liquid 200ml',
    nameHindi: 'जेलुसिल एमपीएस सिरप 200ml',
    genericName: 'Aluminium Hydroxide + Magnesium Hydroxide + Dimethicone',
    brand: 'Gelusil',
    manufacturer: 'Pfizer India',
    description: 'Time-tested antacid for long-lasting acidity relief and soothing stomach lining.',
    usageInstructions: '1-2 teaspoons after food.',
    sideEffects: 'Safe.',
    mrp: 130.00, sellingPrice: 112, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Green Label',
  },

  // --- Category 3: Cold, Cough & Allergy ---
  {
    name: 'Sinarest Tablet',
    nameHindi: 'सिनारेस्ट टैबलेट',
    genericName: 'Paracetamol + Phenylephrine + Chlorpheniramine',
    brand: 'Sinarest',
    manufacturer: 'Centaur Pharmaceuticals',
    description: 'Complete cold and flu formula for blocked nose, sinus headache, watery eyes and sneezing.',
    usageInstructions: '1 tablet 3 times a day after meals.',
    sideEffects: 'Mild drowsiness.',
    mrp: 65.00, sellingPrice: 55, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 3', cover: 'Blue Cover',
  },
  {
    name: 'Cheston Cold Tablet',
    nameHindi: 'चेस्टन कोल्ड टैबलेट',
    genericName: 'Cetirizine 5mg + Paracetamol 325mg + Phenylephrine 10mg',
    brand: 'Cheston Cold',
    manufacturer: 'Cipla Ltd',
    description: 'Triple active cold decongestant tablet for heavy head, runny nose and throat irritation.',
    usageInstructions: '1 tablet twice daily after meals.',
    sideEffects: 'Drowsiness.',
    mrp: 48.00, sellingPrice: 40, discountPercent: 16,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 3', cover: 'Yellow Tag',
  },
  {
    name: 'Allegra 120mg Tablet',
    nameHindi: 'एलेग्रा 120mg टैबलेट',
    genericName: 'Fexofenadine Hydrochloride 120mg',
    brand: 'Allegra',
    manufacturer: 'Sanofi India',
    description: 'Non-drowsy 24-hour allergy relief from dust, pollen, skin rashes, itching and sneezing.',
    usageInstructions: '1 tablet once daily with water. Non-sedating.',
    sideEffects: 'Well-tolerated.',
    mrp: 232.00, sellingPrice: 198, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H', requiresPrescription: true, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 3', cover: 'Green Label',
  },
  {
    name: 'Otrivin Adult Nasal Drops 10ml',
    nameHindi: 'ओट्रिविन नेजल ड्रॉप्स 10ml',
    genericName: 'Xylometazoline Hydrochloride 0.1%',
    brand: 'Otrivin',
    manufacturer: 'GlaxoSmithKline (GSK)',
    description: 'Unblocks congested nose in 25 seconds. Long lasting 12 hour breathing relief.',
    usageInstructions: '2-3 drops in each nostril 2 times daily. Max 5 days.',
    sideEffects: 'Mild transient nasal dryness.',
    mrp: 75.00, sellingPrice: 65, discountPercent: 13,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Benadryl Cough Syrup 100ml',
    nameHindi: 'बेनाड्रिल कफ सिरप 100ml',
    genericName: 'Diphenhydramine + Ammonium Chloride + Sodium Citrate',
    brand: 'Benadryl',
    manufacturer: 'Johnson & Johnson',
    description: 'Relief from wet and dry cough, throat tingling and chest congestion.',
    usageInstructions: '10ml (2 teaspoons) every 4-6 hours.',
    sideEffects: 'Drowsiness.',
    mrp: 140.00, sellingPrice: 120, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 3', cover: 'Red Label',
  },
  {
    name: 'Ascoril-D Plus Cough Syrup 100ml',
    nameHindi: 'एस्कोरिल-डी सिरप 100ml',
    genericName: 'Dextromethorphan + Phenylephrine + Chlorpheniramine',
    brand: 'Ascoril',
    manufacturer: 'Glenmark Pharmaceuticals',
    description: 'Dry cough specialist syrup that suppresses cough reflex and cleans airway passage.',
    usageInstructions: '5ml to 10ml as directed by doctor.',
    sideEffects: 'Mild sedation, dry mouth.',
    mrp: 135.00, sellingPrice: 115, discountPercent: 15,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'H', requiresPrescription: true, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 3', cover: 'Green Label',
  },
  {
    name: 'Vicks VapoRub 50g Tub',
    nameHindi: 'विक्स वेपोरब 50g',
    genericName: 'Menthol + Camphor + Eucalyptus Oil',
    brand: 'Vicks',
    manufacturer: 'Procter & Gamble (P&G)',
    description: 'Topical ointment for relief from 6 cough and cold symptoms and steam inhalation.',
    usageInstructions: 'Rub on chest, throat and back. For steam: 1 spoon in hot water.',
    sideEffects: 'For external use only.',
    mrp: 165.00, sellingPrice: 145, discountPercent: 12,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 2', cover: 'Blue Cover',
  },

  // --- Category 4: Antibiotics (Schedule H / H1) ---
  {
    name: 'Augmentin 625 Duo Tablet',
    nameHindi: 'ऑगमेंटिन 625 डुओ टैबलेट',
    genericName: 'Amoxycillin 500mg + Clavulanic Acid 125mg',
    brand: 'Augmentin',
    manufacturer: 'GlaxoSmithKline (GSK)',
    description: 'Broad spectrum penicillin antibiotic for bacterial infections of chest, ENT, skin and teeth.',
    usageInstructions: 'Take 1 tablet twice daily with food as prescribed. Complete full course.',
    sideEffects: 'Loose stools, mild nausea.',
    mrp: 223.50, sellingPrice: 190, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H1', requiresPrescription: true, categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
  },
  {
    name: 'Azithral 500mg Tablet',
    nameHindi: 'एज़िथ्रल 500mg टैबलेट',
    genericName: 'Azithromycin 500mg',
    brand: 'Azithral',
    manufacturer: 'Alembic Pharmaceuticals',
    description: 'Top macrolide antibiotic for throat infections, tonsillitis, chest infections and typhoid.',
    usageInstructions: '1 tablet once daily for 3-5 days. Take 1 hr before or 2 hrs after meal.',
    sideEffects: 'Abdominal cramp, nausea.',
    mrp: 130.00, sellingPrice: 110, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 5, drugSchedule: 'H', requiresPrescription: true, categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
  },
  {
    name: 'Taxim-O 200mg Tablet',
    nameHindi: 'टैक्सिम-ओ 200mg टैबलेट',
    genericName: 'Cefixime 200mg',
    brand: 'Taxim-O',
    manufacturer: 'Alkem Laboratories',
    description: 'Oral 3rd generation cephalosporin for severe respiratory, urinary tract and typhoid infections.',
    usageInstructions: '1 tablet twice daily with food as prescribed.',
    sideEffects: 'Mild diarrhea, gas.',
    mrp: 115.00, sellingPrice: 98, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H1', requiresPrescription: true, categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
  },
  {
    name: 'Mox 500mg Capsule',
    nameHindi: 'मॉक्स 500mg कैप्सूल',
    genericName: 'Amoxicillin Trihydrate 500mg',
    brand: 'Mox',
    manufacturer: 'Sun Pharmaceutical',
    description: 'Bactericidal antibiotic for bacterial ENT, dental, chest and soft-tissue infections.',
    usageInstructions: '1 capsule 3 times a day as prescribed.',
    sideEffects: 'Skin rash, nausea.',
    mrp: 92.00, sellingPrice: 78, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 3', cover: 'Yellow Tag',
  },
  {
    name: 'Ciplox 500mg Tablet',
    nameHindi: 'सिप्लॉक्स 500mg टैबलेट',
    genericName: 'Ciprofloxacin 500mg',
    brand: 'Ciplox',
    manufacturer: 'Cipla Ltd',
    description: 'Fluoroquinolone antibiotic for bacterial diarrhea, urinary tract, bone and skin infections.',
    usageInstructions: '1 tablet twice daily with plenty of fluids.',
    sideEffects: 'Nausea, joint pain.',
    mrp: 52.00, sellingPrice: 44, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H', requiresPrescription: true, categoryId: 4,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 3', cover: 'Red Label',
  },

  // --- Category 5: Vitamins, Calcium & Energy ---
  {
    name: 'Shelcal 500mg Tablet',
    nameHindi: 'शेलकैल 500mg टैबलेट',
    genericName: 'Calcium 500mg + Vitamin D3 250 IU',
    brand: 'Shelcal',
    manufacturer: 'Torrent Pharmaceuticals',
    description: 'High absorption elemental calcium and Vitamin D3 for bone density and joint strength.',
    usageInstructions: '1 tablet daily after lunch or dinner.',
    sideEffects: 'Safe.',
    mrp: 135.00, sellingPrice: 115, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Green Label',
  },
  {
    name: 'Becosules Z Capsule',
    nameHindi: 'बेकोसूल्स जेड कैप्सूल',
    genericName: 'Vitamin B-Complex + Vitamin C + Zinc',
    brand: 'Becosules',
    manufacturer: 'Pfizer India',
    description: 'Fast healing of mouth ulcers, fatigue, hair health and immunity booster.',
    usageInstructions: '1 capsule daily after breakfast.',
    sideEffects: 'Safe multivitamin.',
    mrp: 55.00, sellingPrice: 47, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 20, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Green Label',
  },
  {
    name: 'Limcee 500mg Chewable Tablet (Orange)',
    nameHindi: 'लिमसी 500mg टैबलेट',
    genericName: 'Vitamin C (Ascorbic Acid) 500mg',
    brand: 'Limcee',
    manufacturer: 'Abbott Healthcare',
    description: 'Delicious chewable Vitamin C for glowing skin, antioxidant defence and viral resistance.',
    usageInstructions: 'Chew 1 tablet daily.',
    sideEffects: 'Safe.',
    mrp: 26.00, sellingPrice: 22, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
  },
  {
    name: 'Neurobion Forte Tablet',
    nameHindi: 'न्यूरोबियन फोर्ट टैबलेट',
    genericName: 'Vitamin B1 + B2 + B3 + B5 + B6 + B12',
    brand: 'Neurobion',
    manufacturer: 'Procter & Gamble (P&G)',
    description: 'Nerve restorative tablet for numbness, tingling in hands/feet, backache and muscular weakness.',
    usageInstructions: '1 tablet daily after food.',
    sideEffects: 'Safe.',
    mrp: 44.00, sellingPrice: 38, discountPercent: 14,
    unitType: 'strip', unitsPerPack: 30, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Evion 400mg Vitamin E Capsule',
    nameHindi: 'एवियन 400mg विटामिन ई कैप्सूल',
    genericName: 'Tocopheryl Acetate (Vitamin E) 400mg',
    brand: 'Evion',
    manufacturer: 'Merck / P&G',
    description: 'Skin nourishment, anti-aging, hair health and muscle recovery.',
    usageInstructions: '1 capsule daily or puncture for topical skin application.',
    sideEffects: 'Safe.',
    mrp: 41.00, sellingPrice: 35, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 2', cover: 'Green Label',
  },
  {
    name: 'Zincovit Daily Tablet',
    nameHindi: 'जिंकोविट टैबलेट',
    genericName: 'Multivitamin + Multimineral + Zinc + Grape Seed Extract',
    brand: 'Zincovit',
    manufacturer: 'Apex Laboratories',
    description: 'Comprehensive daily multivitamin with natural grape seed extract for vitality and immunity.',
    usageInstructions: '1 tablet daily with water after meals.',
    sideEffects: 'Safe.',
    mrp: 110.00, sellingPrice: 94, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 2', cover: 'Yellow Tag',
  },

  // --- Category 6: Pain Gels, Balms & Sprays ---
  {
    name: 'Volini Pain Relief Gel 30g',
    nameHindi: 'वोलिनी जेल 30g',
    genericName: 'Diclofenac Diethylamine + Methyl Salicylate + Menthol',
    brand: 'Volini',
    manufacturer: 'Sun Pharma',
    description: 'Deep micro-gel penetration for neck strain, lower backache, joint stiffness and sprains.',
    usageInstructions: 'Apply gently 3-4 times daily on affected pain area.',
    sideEffects: 'For external use only.',
    mrp: 165.00, sellingPrice: 140, discountPercent: 15,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
  },
  {
    name: 'Moov Pain Relief Cream 50g',
    nameHindi: 'मूव क्रीम 50g',
    genericName: 'Nilgiri Oil + Wintergreen Oil + Mint Extract',
    brand: 'Moov',
    manufacturer: 'Reckitt Benckiser',
    description: '100% Ayurvedic warm action specialist cream for severe back pain and muscular catch.',
    usageInstructions: 'Spread over painful area and massage until fully absorbed.',
    sideEffects: 'Warm soothing sensation.',
    mrp: 215.00, sellingPrice: 185, discountPercent: 14,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Red Label',
  },
  {
    name: 'Zandu Balm 25ml White',
    nameHindi: 'झंडू बाम 25ml',
    genericName: 'Mentha Extract + Gaultheria Oil + Eucalyptus Oil',
    brand: 'Zandu',
    manufacturer: 'Emami Ltd',
    description: 'India\'s No. 1 trusted balm for headache, body pain, cold and nasal block.',
    usageInstructions: 'Gently massage a small amount over forehead or chest.',
    sideEffects: 'Safe for external use.',
    mrp: 95.00, sellingPrice: 82, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 6,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 2', cover: 'Green Label',
  },

  // --- Category 7: Ayurvedic & Immunity ---
  {
    name: 'Dabur Chyawanprash 1kg (2X Immunity)',
    nameHindi: 'डाबर च्यवनप्राश 1kg',
    genericName: 'Amla + Ashwagandha + 41 Ayurvedic Herbs',
    brand: 'Dabur',
    manufacturer: 'Dabur India Ltd',
    description: 'Rich in natural Vitamin C and Ayurvedic herbs for stamina, digestion and seasonal disease defense.',
    usageInstructions: '1-2 teaspoons twice daily with warm milk or water.',
    sideEffects: 'Safe for entire family.',
    mrp: 410.00, sellingPrice: 350, discountPercent: 15,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 3', cover: 'Green Label',
  },
  {
    name: 'Liv.52 DS Tablet 60s',
    nameHindi: 'लिव.52 डीएस टैबलेट 60s',
    genericName: 'Himsra + Kasani Herbal Hepatoprotective Formula',
    brand: 'Himalaya',
    manufacturer: 'Himalaya Wellness',
    description: 'Double strength Ayurvedic liver care tablet. Improves appetite, digestion and liver enzyme levels.',
    usageInstructions: '1-2 tablets twice daily before meals.',
    sideEffects: 'Safe.',
    mrp: 210.00, sellingPrice: 180, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 3', cover: 'Green Label',
  },
  {
    name: 'Patanjali Ashwagandha Capsule 20s',
    nameHindi: 'पतंजलि अश्वगंधा कैप्सूल',
    genericName: 'Withania Somnifera Pure Extract',
    brand: 'Patanjali',
    manufacturer: 'Patanjali Ayurved Ltd',
    description: 'Natural stress reliever, vitality booster and mental focus enhancer.',
    usageInstructions: '1 capsule twice daily with warm milk.',
    sideEffects: 'Safe Ayurvedic herb.',
    mrp: 120.00, sellingPrice: 102, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 20, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
    imageUrl: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 3', cover: 'Yellow Tag',
  },
  {
    name: 'Dabur Pudin Hara Pearls 10s',
    nameHindi: 'डाबर पुदीन हरा पर्ल्स',
    genericName: 'Pudina Satva Mint Oil',
    brand: 'Pudin Hara',
    manufacturer: 'Dabur India',
    description: 'Instant stomach cooling pearls for sudden gas pain, sour burps and indigestion.',
    usageInstructions: '1 pearl with water when acidity occurs.',
    sideEffects: 'Safe.',
    mrp: 30.00, sellingPrice: 26, discountPercent: 13,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Green Label',
  },
  {
    name: 'Koflet Ayurvedic Cough Syrup 100ml',
    nameHindi: 'कोफलेट आयुर्वेदिक कफ सिरप',
    genericName: 'Tulsi + Honey + Licorice + Haritaki',
    brand: 'Himalaya',
    manufacturer: 'Himalaya Wellness',
    description: 'Non-drowsy herbal honey syrup for throat irritation, allergic and smoker cough.',
    usageInstructions: '1-2 teaspoons 3 times a day.',
    sideEffects: 'Safe.',
    mrp: 110.00, sellingPrice: 95, discountPercent: 14,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 7,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 3', cover: 'Yellow Tag',
  },

  // --- Category 8: Diabetes Care & Strips ---
  {
    name: 'Glycomet 500mg Tablet',
    nameHindi: 'ग्लाइकोमेट 500mg टैबलेट',
    genericName: 'Metformin Hydrochloride 500mg',
    brand: 'Glycomet',
    manufacturer: 'USV Pvt Ltd',
    description: 'Gold-standard medicine for blood glucose management in Type-2 diabetes mellitus.',
    usageInstructions: '1 tablet twice daily with or after meals.',
    sideEffects: 'Mild gastrointestinal upset initially.',
    mrp: 38.00, sellingPrice: 32, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'H', requiresPrescription: true, categoryId: 8,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
  },
  {
    name: 'OneTouch Select Plus Test Strips 25s',
    nameHindi: 'वनटच सेलेक्ट प्लस टेस्ट स्ट्रिप्स',
    genericName: 'Blood Glucose Biosensor Strips',
    brand: 'OneTouch',
    manufacturer: 'LifeScan / J&J',
    description: 'Accurate clinical self-test blood sugar strips for OneTouch glucose meter.',
    usageInstructions: 'Apply small blood droplet from lancing device onto test strip tip.',
    sideEffects: 'In vitro diagnostic.',
    mrp: 650.00, sellingPrice: 550, discountPercent: 15,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 8,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 2', cover: 'Yellow Tag',
  },
  {
    name: 'Accu-Chek Active 50 Test Strips',
    nameHindi: 'एक्यू-चेक एक्टिव 50 टेस्ट स्ट्रिप्स',
    genericName: 'Glucose Dehydrogenase Test Strips',
    brand: 'Accu-Chek',
    manufacturer: 'Roche Diabetes Care',
    description: 'Fast 5-second blood sugar testing strips with ISO accuracy standards.',
    usageInstructions: 'Insert in meter and apply capillary blood.',
    sideEffects: 'Diagnostic strip.',
    mrp: 1125.00, sellingPrice: 950, discountPercent: 15,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 8,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 2', cover: 'Green Label',
  },

  // --- Category 9: Heart, BP & Cholesterol ---
  {
    name: 'Telma 40mg Tablet',
    nameHindi: 'टेल्मा 40mg टैबलेट',
    genericName: 'Telmisartan 40mg',
    brand: 'Telma',
    manufacturer: 'Glenmark Pharmaceuticals',
    description: 'Angiotensin receptor blocker for high blood pressure to prevent heart attack and strokes.',
    usageInstructions: '1 tablet once daily at a fixed time.',
    sideEffects: 'Dizziness.',
    mrp: 245.00, sellingPrice: 208, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 9,
    imageUrl: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Red Label',
  },
  {
    name: 'Ecosprin 75mg Tablet',
    nameHindi: 'इकोस्प्रिन 75mg टैबलेट',
    genericName: 'Aspirin Gastro-Resistant 75mg',
    brand: 'Ecosprin',
    manufacturer: 'USV Pvt Ltd',
    description: 'Low-dose antiplatelet blood thinner for cardiovascular protection.',
    usageInstructions: '1 tablet daily after lunch with water as prescribed.',
    sideEffects: 'Mild stomach discomfort.',
    mrp: 12.00, sellingPrice: 10, discountPercent: 16,
    unitType: 'strip', unitsPerPack: 14, drugSchedule: 'H', requiresPrescription: true, categoryId: 9,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Blue Cover',
  },
  {
    name: 'Atorva 10mg Tablet',
    nameHindi: 'एटोरवा 10mg टैबलेट',
    genericName: 'Atorvastatin Calcium 10mg',
    brand: 'Atorva',
    manufacturer: 'Zydus Cadila',
    description: 'Lipid lowering statin that reduces bad cholesterol (LDL) and triglycerides.',
    usageInstructions: '1 tablet once daily at bedtime.',
    sideEffects: 'Mild muscle ache.',
    mrp: 98.00, sellingPrice: 83, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 15, drugSchedule: 'H', requiresPrescription: true, categoryId: 9,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf B', rack: 'Rack 2', cover: 'Green Label',
  },

  // --- Category 10: Baby Care & Pediatric ---
  {
    name: 'Calpol 250mg Pediatric Suspension 60ml',
    nameHindi: 'कैलपोल 250mg सस्पेंशन 60ml',
    genericName: 'Paracetamol 250mg/5ml Strawberry Flavour',
    brand: 'Calpol',
    manufacturer: 'GlaxoSmithKline (GSK)',
    description: 'Fast acting and gentle on children\'s tummy for fever and post-vaccination discomfort.',
    usageInstructions: 'Dose according to pediatrician prescription based on baby weight.',
    sideEffects: 'Safe pediatric medicine.',
    mrp: 54.00, sellingPrice: 46, discountPercent: 15,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 10,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Red Label',
  },
  {
    name: 'Colicaid Drops 15ml with Dropper',
    nameHindi: 'कॉलिकाएड ड्रॉप्स 15ml',
    genericName: 'Simethicone + Dill Oil + Fennel Oil',
    brand: 'Colicaid',
    manufacturer: 'Meyer Organics',
    description: 'Soothing relief for infant colic, tummy bloating, gas pain and continuous crying.',
    usageInstructions: '4-8 drops 15 minutes before feed or as advised by doctor.',
    sideEffects: 'Safe for infants.',
    mrp: 98.00, sellingPrice: 85, discountPercent: 13,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 10,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Yellow Tag',
  },
  {
    name: 'Woodward\'s Gripe Water 130ml',
    nameHindi: 'वुडवर्ड्स ग्राइप वाटर 130ml',
    genericName: 'Dill Seed Oil + Sarjikakshara Ayurvedic',
    brand: 'Woodward\'s',
    manufacturer: 'TTK Healthcare',
    description: 'Relieves teething pain, hiccups and digestive distress in growing babies.',
    usageInstructions: '1-2 teaspoons according to age.',
    sideEffects: 'Safe herbal gripe water.',
    mrp: 65.00, sellingPrice: 58, discountPercent: 11,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 10,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf C', rack: 'Rack 1', cover: 'Blue Cover',
  },

  // --- Category 11: Eye, Ear & First Aid ---
  {
    name: 'Ciplox Eye/Ear Drops 10ml',
    nameHindi: 'सिप्लॉक्स आई/ईयर ड्रॉप्स 10ml',
    genericName: 'Ciprofloxacin 0.3% w/v Ophthalmic Solution',
    brand: 'Ciplox',
    manufacturer: 'Cipla Ltd',
    description: 'Sterile antibacterial solution for eye infections, conjunctivitis, stye and ear infection.',
    usageInstructions: '1-2 drops in affected eye/ear 3-4 times daily as prescribed.',
    sideEffects: 'Mild transient burning.',
    mrp: 24.00, sellingPrice: 20, discountPercent: 16,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'H', requiresPrescription: true, categoryId: 11,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Blue Cover',
  },
  {
    name: 'Band-Aid Medicated Classic Strips 10s',
    nameHindi: 'बैंड-एड क्लासिक 10s',
    genericName: 'Medicated Antiseptic Adhesive Strips',
    brand: 'Band-Aid',
    manufacturer: 'Johnson & Johnson',
    description: 'Water resistant bandage for minor cuts, burns and scrapes.',
    usageInstructions: 'Clean wound and stick bandage firmly. Change daily.',
    sideEffects: 'Safe.',
    mrp: 45.00, sellingPrice: 38, discountPercent: 15,
    unitType: 'strip', unitsPerPack: 10, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 11,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Blue Cover',
  },
  {
    name: 'Dettol Antiseptic Liquid 100ml',
    nameHindi: 'डेटॉल एंटीसेप्टिक लिक्विड 100ml',
    genericName: 'Chloroxylenol 4.8% w/v Antiseptic',
    brand: 'Dettol',
    manufacturer: 'Reckitt Benckiser',
    description: 'Protects from 100 illness causing germs. First aid wound washing and personal hygiene.',
    usageInstructions: 'Dilute with water (1 cap in 1 mug) for cuts and scrapes.',
    sideEffects: 'External use only.',
    mrp: 45.00, sellingPrice: 40, discountPercent: 11,
    unitType: 'bottle', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 11,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Green Label',
  },

  // --- Category 12: Skin Care & Antiseptics ---
  {
    name: 'Betadine 5% Antiseptic Ointment 20g',
    nameHindi: 'बेटाडाइन 5% ऑइंटमेंट 20g',
    genericName: 'Povidone Iodine 5% w/w',
    brand: 'Betadine',
    manufacturer: 'Win-Medicare',
    description: 'Top microbicidal water-soluble ointment for fresh cuts, open wounds, burns and infections.',
    usageInstructions: 'Clean wound and apply small amount directly onto area 1-2 times daily.',
    sideEffects: 'Mild temporary stinging.',
    mrp: 85.00, sellingPrice: 72, discountPercent: 15,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Yellow Tag',
  },
  {
    name: 'Soframycin Skin Cream 30g',
    nameHindi: 'सोफ्रामाइसिन क्रीम 30g',
    genericName: 'Framycetin Sulphate 1% w/w',
    brand: 'Soframycin',
    manufacturer: 'Sanofi India',
    description: 'Antibacterial skin healing cream for boils, cuts, ulcers, burns and infected eczema.',
    usageInstructions: 'Apply thin layer 2-3 times daily on affected skin.',
    sideEffects: 'Safe for skin use.',
    mrp: 62.00, sellingPrice: 53, discountPercent: 15,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'H', requiresPrescription: true, categoryId: 12,
    imageUrl: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Green Label',
  },
  {
    name: 'Candid-B Cream 20g',
    nameHindi: 'कैंडिड-बी क्रीम 20g',
    genericName: 'Clotrimazole 1% + Beclomethasone 0.025%',
    brand: 'Candid-B',
    manufacturer: 'Glenmark Pharmaceuticals',
    description: 'Dual antifungal and anti-inflammatory cream for fungal infections, ringworm and skin itchiness.',
    usageInstructions: 'Apply sparingly to affected areas twice daily.',
    sideEffects: 'Skin thinning if overused.',
    mrp: 185.00, sellingPrice: 158, discountPercent: 15,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'H', requiresPrescription: true, categoryId: 12,
    imageUrl: 'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&auto=format&fit=crop&q=80',
    shelf: 'Shelf A', rack: 'Rack 2', cover: 'Red Label',
  },
  {
    name: 'Itch Guard Plus Cream 20g',
    nameHindi: 'इच गार्ड प्लस क्रीम 20g',
    genericName: 'Terbinafine Hydrochloride + Miconazole',
    brand: 'Itch Guard',
    manufacturer: 'Piramal Healthcare',
    description: 'Fast relief from fungal ringworm (Daad), jock itch, underarm itching and skin redness.',
    usageInstructions: 'Wash, dry and apply twice daily for 7-14 days.',
    sideEffects: 'Mild cooling sensation.',
    mrp: 110.00, sellingPrice: 95, discountPercent: 14,
    unitType: 'tube', unitsPerPack: 1, drugSchedule: 'OTC', requiresPrescription: false, categoryId: 12,
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
    shelf: 'Counter Shelf', rack: 'Rack 1', cover: 'Yellow Tag',
  },
]

async function seedMaster() {
  console.log('🚀 Loading Complete Indian Retail Pharmacy Master Catalog (42+ top medicines)...')

  for (const med of comprehensiveIndianMedicines) {
    const existing = await prisma.medicine.findFirst({ where: { name: med.name } })

    let medicineId: number
    if (existing) {
      const updated = await prisma.medicine.update({
        where: { id: existing.id },
        data: {
          name: med.name,
          nameHindi: med.nameHindi,
          genericName: med.genericName,
          brand: med.brand,
          manufacturer: med.manufacturer,
          description: med.description,
          usageInstructions: med.usageInstructions,
          sideEffects: med.sideEffects,
          mrp: med.mrp,
          sellingPrice: med.sellingPrice,
          discountPercent: med.discountPercent,
          unitType: med.unitType,
          unitsPerPack: med.unitsPerPack,
          drugSchedule: med.drugSchedule,
          requiresPrescription: med.requiresPrescription,
          categoryId: med.categoryId,
          imageUrl: med.imageUrl,
          isActive: true,
        },
      })
      medicineId = updated.id
    } else {
      const created = await prisma.medicine.create({
        data: {
          name: med.name,
          nameHindi: med.nameHindi,
          genericName: med.genericName,
          brand: med.brand,
          manufacturer: med.manufacturer,
          description: med.description,
          usageInstructions: med.usageInstructions,
          sideEffects: med.sideEffects,
          mrp: med.mrp,
          sellingPrice: med.sellingPrice,
          discountPercent: med.discountPercent,
          unitType: med.unitType,
          unitsPerPack: med.unitsPerPack,
          drugSchedule: med.drugSchedule,
          requiresPrescription: med.requiresPrescription,
          categoryId: med.categoryId,
          imageUrl: med.imageUrl,
          isActive: true,
        },
      })
      medicineId = created.id
    }

    // Active stock batch (Safe shelf life: Dec 2028)
    const existingBatch = await prisma.medicineBatch.findFirst({
      where: { medicineId },
    })

    if (!existingBatch) {
      await prisma.medicineBatch.create({
        data: {
          medicineId,
          batchNumber: `BATCH-HH-${medicineId.toString().padStart(4, '0')}-2028`,
          expiryDate: new Date('2028-12-31'),
          totalQuantity: 300,
          currentQuantity: 300,
          purchasePrice: Math.round(med.sellingPrice * 0.75),
        },
      })
    }

    // Physical store placement
    await prisma.medicineLocation.upsert({
      where: { medicineId },
      update: {
        shelfLabel: med.shelf,
        rackNumber: med.rack,
        section: 'Middle',
        coverLabel: med.cover,
        description: 'Main dispensary rack',
      },
      create: {
        medicineId,
        shelfLabel: med.shelf,
        rackNumber: med.rack,
        section: 'Middle',
        coverLabel: med.cover,
        description: 'Main dispensary rack',
      },
    })
  }

  console.log(`✅ Master Catalog successfully loaded into database (${comprehensiveIndianMedicines.length} medicines ready with high-res photos)!`)
}

seedMaster()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
